### ISSUE TITLE
Unknown field error

### ISSUE THREAD

**Issue by lydiatsai** [scholarslab/SolrSearch#110]
Hi all. I am new to Omeka and Solr, so any help would be greatly appreciated.

I have installed the plug-in and selected the fields I want to index and to become facets. Now I am trying to turn my private items into public items so they can be indexed. However, whenever I try to make an item public, I get this error:

Omeka has encountered an error

Apache_Solr_HttpTransportException
'400' Status: Bad Request

#0 /var/www/html/omeka/plugins/SolrSearch/lib/solr-php-client/Service.php(669): Apache_Solr_Service->_sendRawPost('http://localhos...', '<add><doc><fiel...')
#1 /var/www/html/omeka/plugins/SolrSearch/lib/solr-php-client/Service.php(737): Apache_Solr_Service->add('<add><doc><fiel...')
#2 /var/www/html/omeka/plugins/SolrSearch/SolrSearchPlugin.php(195): Apache_Solr_Service->addDocuments(Array)
#3 [internal function]: SolrSearchPlugin->hookAfterSaveItem(Array)
#4 /var/www/html/omeka/application/libraries/Omeka/Plugin/Broker.php(157): call_user_func(Array, Array)
#5 /var/www/html/omeka/application/libraries/Omeka/Record/AbstractRecord.php(298): Omeka_Plugin_Broker->callHook('after_save_item', Array)
#6 /var/www/html/omeka/application/libraries/Omeka/Record/AbstractRecord.php(550): Omeka_Record_AbstractRecord->runCallbacks('afterSave', Array)
#7 /var/www/html/omeka/application/libraries/Omeka/Controller/AbstractActionController.php(209): Omeka_Record_AbstractRecord->save(false)
#8 /var/www/html/omeka/application/controllers/ItemsController.php(89): Omeka_Controller_AbstractActionController->editAction()
#9 /var/www/html/omeka/application/libraries/Zend/Controller/Action.php(516): ItemsController->editAction()
#10 /var/www/html/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('editAction')
#11 /var/www/html/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()
#13 /var/www/html/omeka/application/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/html/omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#15 /var/www/html/omeka/admin/index.php(28): Omeka_Application->run()
#16 {main}

In addition, my Solr dashboard logs this error:

org.apache.solr.common.SolrException: ERROR: [doc=Item_219] unknown field 'resulttype'
	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:185)
	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:78)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:238)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:164)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:926)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1080)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:692)
	at org.apache.solr.update.processor.LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:100)
	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:247)
	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:174)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:99)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:74)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1967)
	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:777)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)

Any ideas on what is happening and how this can be resolved?

**Comment by lydiatsai** [comment]
Thank you for your help. The error no longer appears and searches are working.

**Comment by erochest** [comment]
Great. Glad to hear it.
